### PR TITLE
Issues with the old standalone GUI

### PR DESCRIPTION
**Pull request by am202**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@am202 can you create a ticket describing what these issues are?

**Comment by am202** [comment]
@dkayiwa OK, I just created https://issues.openmrs.org/browse/PTM-67

**Comment by mhawila** [comment]
@am202 could you add unit tests for these changes?

**Comment by am202** [comment]
@mhawila OK, I just committed api/src/test/java/org/regenstrief/linkage/util/LinkDataSourceTest.java

**Pull request merged**
