### PR TITLE
PTM-83: Save and update incremental patient matching report to the database

### PR DESCRIPTION
**Pull request by Lahiru-J**
To save the changes in incremental patient matching process, it is required to load an existing report to write the changes to the same report and to save it.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Do you mind squashing the commits into one?

**Comment by dkayiwa** [comment]
@bmamlin what do you think of this? 😊

**Comment by dkayiwa** [comment]
@bmamlin ping 😊

**Comment by dkayiwa** [comment]
@Lahiru-J are you still interested in finishing this up?

**Comment by Lahiru-J** [comment]
@dkayiwa Yes, I've been waiting until this get reviewed

**Comment by dkayiwa** [comment]
@Lahiru-J can you always include a link to the ticket as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
Ping me to reopen this when you are ready to continue working on it.

**Pull request closed without merging**
