### PR TITLE
GCI-284: Add error message to the Patient Matching module

### PR DESCRIPTION
**Pull request by samuelpiltch**
https://issues.openmrs.org/browse/GCI-284

### CODE REVIEW

**Comment by samuelmale** [comment]
Could you revamp your commit message and the PR title as well prior to the tips I shared?

Something like "branch_name: 'descriptive summary of your changes'" eg "TRUNK-11: Removed unused imports from foo.java file"

Make sure that you also prove the link to the original Jira ticket you have worked in the PR description

**Comment by samuelpiltch** [comment]
Updated commit title

**Comment by samuelmale** [comment]
@samuelpiltch The PR title is fine, thanks for the good job but the issue if with the commit message. Like in a nutshell, instead of using "add" could you use "added" because you really added. Basically the used of a commit message to describe what was done in that commit not what is expected to be done.

**Comment by samuelpiltch** [comment]
@samuelmale I've been under the assumption that it's GitHub convention to write commit messages in the imperative. This convention matches up with commit messages generated by commands like git merge and git revert and is followed by many large organizations (i.e.: Facebook, Google).

**Comment by samuelmale** [comment]
Cool, that makes sense to me.

**Comment by samuelmale** [comment]
I got details on that here https://chris.beams.io/posts/git-commit/#imperative

Thanks @samuelpiltch

**Comment by samuelmale** [comment]
@samuelpiltch are you able to claim this and change its status to code review so that we get this merged? https://issues.openmrs.org/browse/GCI-284

**Pull request merged**
