### PR TITLE
PTM-84: Functionality to support two datasources

### PR DESCRIPTION
**Pull request by Lahiru-J**
Provide the support to perform patient matching using two datasources other than deduplication.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Lahiru-J are you still interested in finishing this up?

**Comment by Lahiru-J** [comment]
@dkayiwa Yes, I've been waiting until this get reviewed so I can update the code base accordingly

**Comment by dkayiwa** [comment]
@Lahiru-J can you always include a link to the ticket as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
Ping me to reopen this when you are ready to continue working on it.

**Pull request closed without merging**
